In [1]:
import numpy as np

In [7]:
array = np.random.normal(loc=1, scale=10, size=(1000, 50))

In [14]:
m, std = np.mean(array, axis=0), np.std(array, axis=0)
array_norm = (array - m) / std

In [15]:
array_norm

array([[-0.39966835,  1.24024317, -0.49868075, ..., -1.06688255,
        -1.23475119, -1.09141283],
       [-0.20916931, -0.865394  , -0.04686218, ..., -0.83433155,
        -1.75243406,  0.09236604],
       [ 1.10954815,  0.57580616,  1.05244127, ...,  0.614528  ,
         1.27166105,  0.22356807],
       ..., 
       [ 0.34671997,  0.78606976, -0.97651445, ...,  0.60906246,
         0.84084454,  0.89838984],
       [-0.04659199,  0.61399591,  0.7722059 , ...,  0.69631727,
        -0.15865687, -3.43409796],
       [-0.10067469,  0.33065714,  1.07912655, ..., -0.0837559 ,
        -0.71177695, -0.23012692]])

In [16]:
Z = np.array([[4, 5, 0], 
             [1, 9, 3],              
             [5, 1, 1],
             [3, 3, 3], 
             [9, 9, 9], 
             [4, 7, 1]])

In [26]:
r = np.sum(Z, axis=1)
print r
print np.nonzero(r > 10)

[ 9 13  7  9 27 12]
(array([1, 4, 5]),)


In [27]:
A = np.eye(3)
B = np.eye(3)
print A
print B

[[ 1.  0.  0.]
 [ 0.  1.  0.]
 [ 0.  0.  1.]]
[[ 1.  0.  0.]
 [ 0.  1.  0.]
 [ 0.  0.  1.]]


In [32]:
sum_matrix = np.vstack((A, B))
sum_matrix

array([[ 1.,  0.,  0.],
       [ 0.,  1.,  0.],
       [ 0.,  0.,  1.],
       [ 1.,  0.,  0.],
       [ 0.,  1.,  0.],
       [ 0.,  0.,  1.]])